// Maps real Wix collection names -> your categoryGroups.ts category slugs
export const wixCategoryMap: Record<string, string> = {
  "Hats": "hats",
  "Beanies": "beanies",
  "Jackets": "jackets",
  "Sweatshirts": "sweatshirts",
  "Sweatpants": "sweatpants",
  "T-Shirts": "tees",
  "Tank Tops": "tank-tops",
  "Long Sleeve T-Shirts": "long-sleeves",
  "Embroidered T-Shirts": "tees",
  "Youth": "youth",
  "Custom Apparel": "custom-apparel",
  "Custom Headwear": "custom-headwear",
  "ACCESSORIES": "accessories",
  "Stickers": "stickers",
  "Challenge Coins": "challenge-coins",
  "Pre-owned Leather Helmets": "leather-helmets",
  "Custom Fire Flags": "custom-fire-flags",
  "New Arrivals": "new-arrivals",
};

// Maps real Wix collection names -> your brands.ts brand slugs
export const wixBrandMap: Record<string, string> = {
  "San Francisco Fire Department": "sffd",
  "San Francisco Police Department": "sfpd",
  "Richmond Fire Dept.": "richmond-fire",
  "Colma Fire District": "colma-fire",
  "HMB Volunteer Fire Dept.": "hmb-volunteer-fire",
  "Vallejo Leatherheads": "vallejo-leatherheads",
  "SFFD Cross Axe": "sffd-cross-axe",
  "SFFD Golf Club": "sffd-golf-club",
  "SFFD Hockey Club": "sffd-hockey",
  "SFFD K9": "sffd-k9",
  "SFFD Los Bomberos": "sffd-los-bomberos",
  "SFFD Station Apparel": "sffd-station-apparel",
  "SFFCPF": "sffcpf",
  "SF Fire Ner Tamid Society": "sf-fire-ner-tamid",
  "Front Seat Academy": "front-seat-academy",
  "Richmond Youth Academy": "richmond-youth-academy",
  "SF Behavioral Health Foundation": "sf-behavioral-health",
  "Street Crisis | Community Paramedics": "street-crisis",
  "United Fire Service Women Apparel": "ufsw",
  "Asian Firefighters Association": "asian-firefighters-association",
  "2 Eleven Shields": "2-eleven-shields",
  "Bay Area Fire Store Apparel": "bay-area-fire-store",
  "2026 Bay Area Fire Conference Apparel": "bay-area-fire-conference",
  "Fight Fire, Get Dirty": "fight-fire-get-dirty",
  "Keep Fire In Your Life | Flow and Move": "keep-fire-in-your-life",
  "Fire Nuggets": "fire-nuggets",
  "Palo Alto Fire Dept.": "palo-alto-fire", 
};